import {test,expect} from "@playwright/test";
test("all pages load without script errors or horizontal overflow",async({page})=>{
 const errors=[];page.on("pageerror",e=>errors.push(e.message));
 for(const path of ["index.html","buyer.html","seller.html","properties.html","portfolios.html","portfolio.html","auction.html","payment.html"]){
  await page.goto("/"+path);
  await expect(page.locator("[data-mode-label]")).toContainText("Test mode");
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
 }
 expect(errors).toEqual([]);
});
test("buyer payment gate, bidding, persistent outcome and both perspectives",async({page})=>{
 await page.goto("/buyer.html?auction=demo-property&address=4218%20Maple%20Ridge%20Drive");
 await page.locator("#buyer-name").fill("Test Participant");
 await page.locator("#buyer-email").fill("buyer@example.com");
 await page.locator("#buyer-confirmation").check();
 await page.getByRole("button",{name:"Submit Buyer Interest",exact:true}).click();
 await expect(page).toHaveURL(/payment.html/);
 await page.locator("#payment-submit").click();
 await expect(page.locator("#payment-message")).toContainText("confirm");
 await page.locator("#payment-consent").check();
 await page.locator("#payment-submit").click();
 await expect(page).toHaveURL(/auction.html/);
 await expect(page.locator("#bid-form")).toBeVisible();
 await page.locator("#bid-amount").fill("500000");
 await page.locator("#bid-consent").check();
 await page.getByRole("button",{name:"Place bid",exact:true}).click();
 await expect(page.locator("#auction-highest")).toHaveText("$500,000");
 await page.reload();
 await expect(page.locator("#auction-highest")).toHaveText("$500,000");
 await page.locator("#test-controls summary").click();
 await page.locator("#finish-auction").click();
 await expect(page.locator("#auction-result")).toContainText("Your bid won");
 await expect(page.locator(".signal-green")).toBeVisible();
 await expect(page.locator("#bid-form")).toBeHidden();
 await page.reload();
 await expect(page.locator("#auction-result")).toContainText("Your bid won");
 await page.locator("#test-controls summary").click();
 await page.locator("#test-actor").selectOption("test-buyer-a");
 await expect(page.locator("#auction-result")).toContainText("did not win");
 await expect(page.locator(".signal-red")).toBeVisible();
 await page.locator("#test-actor").selectOption("test-seller");
 await expect(page.locator(".seller-winning-price")).toHaveText("$500,000");
 await expect(page.locator("#seller-fee-due")).toHaveText("$0");
 await expect(page.locator("#bid-history tr")).toHaveCount(4);
 await page.locator("#complete-sale").click();
 await expect(page.locator("#seller-fee-due")).toHaveText("$1,000");
});
test("portfolio spreadsheet filters and actual Excel upload create a complete listing",async({page})=>{
 await page.goto("/buyer.html");
 await expect(page.locator(".portfolio-entry")).toHaveCount(0);
 await page.getByRole("link",{name:"Search Available Portfolios",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Available Portfolios",exact:true})).toBeVisible();
 await expect(page.locator(".portfolio-entry")).toHaveCount(1);
 await page.locator(".portfolio-entry").click();
 await expect(page).toHaveURL(/\/portfolio\.html$/);
 await expect(page.locator("#portfolio-count")).toHaveText("150");
 await expect(page.locator("#portfolio-price")).toHaveText("$4,804,450");
 await expect(page.locator("#portfolio-table-body tr")).toHaveCount(150);
 await page.locator("#portfolio-condition").selectOption("Good");
 await expect(page.locator("#portfolio-table-body tr")).toHaveCount(60);
 const xlsx=await page.request.get("/data/REO-150-properties.xlsx");
 expect(xlsx.ok()).toBeTruthy();
 expect((await xlsx.body()).subarray(0,2).toString()).toBe("PK");
 await page.goto("/seller.html?kind=portfolio");
 await expect(page.locator("#single-fields")).toBeHidden();
 await page.locator("#portfolio-title").fill("Uploaded REO Portfolio");
 await page.locator("#portfolio-file").setInputFiles("data/REO-150-properties.xlsx");
 await expect(page.locator("#portfolio-upload-message")).toContainText("150 properties imported",{timeout:20000});
 await page.locator("#seller-minimum").fill("4803450");
 await page.locator("#seller-name").fill("Portfolio Seller");
 await page.locator("#seller-email").fill("seller@example.com");
 await page.locator("#seller-fee-consent").check();
 await page.locator("#seller-confirmation").check();
 await page.getByRole("button",{name:"Submit Property Information",exact:true}).click();
 await expect(page).toHaveURL(/payment.html/);
 await page.locator("#payment-consent").check();
 await page.locator("#payment-submit").click();
 await expect(page).toHaveURL(/auction.html/);
 await expect(page.locator("#auction-title")).toHaveText("Uploaded REO Portfolio");
 await expect(page.locator("#seller-reserve")).toHaveText("$4,804,450");
 await page.goto("/properties.html");
 await expect(page.locator(".portfolio-entry")).toHaveCount(0);
 await expect(page.locator("#new-listings")).not.toContainText("Uploaded REO Portfolio");
 await page.goto("/portfolios.html");
 await expect(page.locator("#new-listings")).toContainText("Uploaded REO Portfolio");
 await page.locator("#new-listings .portfolio-entry").click();
 await expect(page.locator("#portfolio-count")).toHaveText("150");
 await expect(page.locator("#portfolio-data-label")).toHaveText("Seller-provided portfolio data");
});
test("malformed portfolio input is rejected with a clear message",async({page})=>{
 await page.goto("/seller.html?kind=portfolio");
 await page.locator("#portfolio-file").setInputFiles({name:"bad.csv",mimeType:"text/csv",buffer:Buffer.from("Asset ID,Address,City,State,Condition,Reference Value\nA,1 Test St,Dallas,TX,Good,-100")});
 await expect(page.locator("#portfolio-upload-message")).toContainText("Reference Value must be a positive");
 expect(await page.locator("#portfolio-file").evaluate(el=>el.validity.valid)).toBe(false);
});
